name: Reusable - Build and Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      service:
        description: 'Service name'
        required: true
        type: string
      environment:
        description: 'Environment to deploy'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load Terraform variables
        run: |
          echo "Loading variables from deploy.tfvars"
          grep -v '^#' deploy.tfvars | sed 's/ *= */=/' | while read line; do
            key=$(echo "$line" | cut -d= -f1)
            value=$(echo "$line" | cut -d= -f2)
            echo "${key}=${value}" >> $GITHUB_ENV
          done

      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth gcloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: "infra-automation-global@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          workload_identity_provider: "projects/644009734493/locations/global/workloadIdentityPools/github/providers/github-repo-provider"

      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.auth_token }}
          registry: ${{ env.region }}-docker.pkg.${{ inputs.environment }}

      - name: Build and Push Container
        run: |
          IMAGE_URI="${{ env.region }}-docker.pkg.${{ inputs.environment }}/${{ env.project_id }}/${{ env.artifact_repository_id }}/${{ inputs.service }}:${{ inputs.environment }}"
          echo "IMAGE_URI=$IMAGE_URI"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push' && inputs.environment == 'dev') ||
          (github.event_name == 'workflow_dispatch' && inputs.environment != 'dev')
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "${{ inputs.service }}-${{ inputs.environment }}"
          region: ${{ env.region }}
          image: "${{ env.region }}-docker.pkg.${{ inputs.environment }}/${{ env.project_id }}/${{ env.artifact_repository_id }}/${{ inputs.service }}:${{ inputs.environment }}"

      - name: Show output
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push' && inputs.environment == 'dev') ||
          (github.event_name == 'workflow_dispatch' && inputs.environment != 'dev')
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"

