name: Terraform Apply

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    uses: .github/workflows/reusable-terraform-apply.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_BUCKET: ${{ secrets.GCP_BUCKET }}