name: 'Terraform'

on:
  pull_request:
    branches: ["main"]          # Run plan on PRs targeting main
  push:
    branches: ["main"]          # Trigger for auto-apply in dev
  workflow_dispatch:             # Manual trigger for stage/prod
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    ## injected by github into terraform variables
    env:
      TF_VAR_environment: ${{ github.event.inputs.environment || 'dev' }}
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_gcp_bucket: ${{ secrets.GCP_BUCKET }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup gcloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: "infra-automation-global@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          workload_identity_provider: "projects/644009734493/locations/global/workloadIdentityPools/github/providers/github-repo-provider"

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.GCP_BUCKET }}" \
            -backend-config="prefix=${{ github.event.inputs.environment || 'dev' }}"

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: terraform
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push' && (github.event.inputs.environment == 'dev' || github.event.inputs.environment == '')) ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.environment != 'dev')
        run: terraform apply -auto-approve -input=false

